name: Listing S3 Buckets

on: 
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
  
jobs:
  listing_buckets:
    runs-on: ubuntu-latest
    steps:
      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: List S3 Buckets
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
         echo "Listing S3 Buckets"
         aws s3 ls

      